env:
  node: true
  es6: true
  jest: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  project: [./tsconfig.eslint.json]
  sourceType: module
plugins:
  - '@typescript-eslint'
  - import
  - prettier
settings:
  import/resolver:
    typescript:
      project: ./tsconfig.json
    node:
      paths: [src, nodes_modules]
  import/parsers:
    '@typescript-eslint/parser': [.ts]
ignorePatterns: [/dist]

rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - avoidEscape: true
      allowTemplateLiterals: false
  semi:
    - error
    - never
  comma-dangle:
    - error
    - always-multiline

  no-unused-vars: off
  '@typescript-eslint/no-unused-vars': error

  import/newline-after-import: error
  import/no-default-export: error
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - [parent, sibling]
        - index
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true
  import/no-internal-modules:
    - error

  '@typescript-eslint/naming-convention':
    - error
    - selector: function
      format: [camelCase, PascalCase]
    - selector: variable
      format: [camelCase, PascalCase, UPPER_CASE]
    - selector: [class, interface, typeAlias, typeParameter, enum]
      format: [PascalCase]
